train:
  epochs: 200
  batch: 32
  imgsz: 640
  lr0: 0.0055
  patience: 10
  optimizer: "SGD"
  plots: true
  workers: 8

resize_bboxes:
  enable: true
  min_object_size: 32
  max_object_size: 300
  center_objects: true
